site_name: 'NGSI-LD Smart Farm Tutorials'
site_url: 'https://ngsi-ld.tutorials.readthedocs.org'
repo_url: 'https://github.com/fiware/tutorials.NGSI-LD'
site_description: FIWARE NGSI-LD Tutorial Documentation (Smart Farm)
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
markdown_extensions:
  - fenced_code
extra_css:
  - 'https://fiware.github.io/catalogue/style/fiware_readthedocs.css'
  - 'https://fiware.github.io/catalogue/style/fiware_readthedocs_neutral.css'
  - 'https://fiware.github.io/catalogue/ngsi-ld.css'
nav:
  - Home: index.md
  - '<span style=''font-size:105%;padding:0px''>Core Context Management: </span><span style=''font-size:105%;padding:0px''>The NGSI-LD Interface</span>':
      - Understanding @context: understanding-@context.md
      - Working with @context: working-with-@context.md
      - Normalized CRUD Operations: ngsi-ld-operations.md
      - Concise CRUD Operations: concise.md
      - Merge Patch and Put: merge-patch.md
      - Entity Relationships: entity-relationships.md
      - Subscriptions: subscriptions.md
      - Registrations: context-providers.md
      - Temporal Operations: short-term-history.md
      - Extended Properties: extended-properties.md
  - IoT Agents & Robots:
      - IoT Sensors: iot-sensors.md
      - IoT Agent (Ultralight): iot-agent.md
      - IoT Agent (JSON): iot-agent-json.md
  - '<span style=''font-size:105%;padding:0px''>Core Context Management: </span><span style=''font-size:105%;padding:0px''>Processing & History Management</span>':
      - Time-Series Data: time-series-data.md
      - Big Data Analysis (Flink): big-data-flink.md
      - Big Data Analysis (Spark): big-data-spark.md
  - Identity Management:
      - Administrating Users: identity-management.md
      - Managing Roles and Permissions: roles-permissions.md
      - Verifiable Credentials: verifiable-credentials.md
  - 'Processing, Analysis and Visualization':
      - Cloud Edge Computing: edge-computing.md
  - Integrating NGSI-v2 Systems:
      - Federative Data Spaces: linked-data.md
  - Appendix:
      - Data Models: datamodels.md
      - Installing Docker: docker-ubuntu.md
      - Using Virtual Box: virtual-box.md
      - Using WSL: wsl.md
      - Troubleshooting: troubleshooting.md
